name: 'Jest evaluator'
description: 'Jest evaluator action for Tryber projects'
inputs:
  npm-start:
    description: 'Run npm start and waits to url before testing'
    default: false
  wait-for:
    description: 'Url that npm start command waits for'
    default: 'http://localhost:3000'
outputs:
  result:
    description: 'Jest unit tests JSON results in base64 format.'
  pr-number:
    description: 'Pull Request number that trigger build.'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.npm-start }}
    - ${{ inputs.wait-for }}
